### ISSUE TITLE
Create quickinfo rendering in post-meta for projects

### ISSUE THREAD

**Issue by MarauderXtreme** [MarauderXtreme/kepler.international#18]
Currently every post only has the posted and the last-updated time as well as the assigned tags.
For projects it could be useful to define a frontmatter structure for various quickinfo.

```yml
---
project:
  url: https://example.com
  repo: https://github.com/example/repo
  state: finished
  languages: yml
---
```
